
services:
  db:
    image: postgres:18
    container_name: dino_wallet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dino_wallet
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql

  api:
    build: .
    container_name: dino_wallet_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespassword@db:5432/dino_wallet?schema=public"
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "pnpm run prisma:migrate:prod && pnpm run db:seed:prod && pnpm run start"

volumes:
  postgres-data:
